# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=6)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
